version: "3"
services:
  reverseproxy:
      image: yaacinezidelmal/reverseproxy
      ports:
          - 80:80
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: yaacinezidelmal/udacity-restapi-user
    environment:
      Postgres_username: $Postgres_username
      Postgres_password: $Postgres_password 
      Postgres_database: $Postgres_database 
      Postgres_host: $Postgres_host 
      Postgres_aws_region: $Postgres_aws_region 
      Postgres_aws_profile: $Postgres_aws_profile 
      Postgres_aws_media_bucket: $Postgres_aws_media_bucket
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: yaacinezidelmal/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      Postgres_username: $Postgres_username
      Postgres_password: $Postgres_password 
      Postgres_database: $Postgres_database 
      Postgres_host: $Postgres_host 
      Postgres_aws_region: $Postgres_aws_region 
      Postgres_aws_profile: $Postgres_aws_profile 
      Postgres_aws_media_bucket: $Postgres_aws_media_bucket
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: yaacinezidelmal/udacity-frontend:local
    ports:
      - "8100:80"
